data_ingestion:
  file_path: air-passengers.csv

data_processing:
  date_columns:
    - "Month"
  int_columns:
    - "#Passengers"
  column_name_mapping:
    "Month" : "date"
    "#Passengers" : "y"

train_test_split:
  train_ratio: 0.7
  dev_ratio: 0.15
  test_ratio: 0.15

target:
  variable_name: "target"

random_forest_parameters:
  n_estimators: 50
  max_depth: 4
  min_samples_split: 2
  min_samples_leaf: 1
  random_state: 42
